User.create(user_name: "hello", user_email: "hello@gmail.com", password: "123")
User.create(user_name: "hello1", user_email: "hello1@gmail.com", password: "123")
BubbleTea.create(name: "greenbobo", user_id: 1, flavor: "green")
BubbleTea.create(name: "green", user_id: 2, flavor: "green")
Ingredient.create(name: "Tapioca")
Ingredient.create(name: "Coconut Jelly")
Ingredient.create(name: "Red Bean")
Ingredient.create(name: "Pop Jelly")
Ingredient.create(name: "Brown Sugar Tapioca")
Ingredient.create(name: "Aloe")
BubbleTea.create(flavor: "Green Tea")
BubbleTea.create(flavor: "Black Tea")
BubbleTea.create(flavor: "Oolong Tea")

